name: Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-in-project: true
      - name: Load cached venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-docs-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          poetry install --no-interaction --with docs
          poetry run pip install torch --index-url https://download.pytorch.org/whl/cpu --force-reinstall
      - name: Build docs
        run: poetry run mkdocs build
      - name: Deploy to pysignet.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          external_repository: pysignet/pysignet.github.io
          publish_branch: main
          publish_dir: ./site
